copyright_name: 'Philippe Pasquin (Shopify Developer)'
voir_le_prix: 'See the price'
voir_les_prix: 'See the prices'
request_price: 'Request an estimate'
commencons: "Let's get started!"
subheading: 'Tailored support on Shopify'
heading: 'Delegate your Shopify development tasks.'
description: 'Choose a plan that works for you'
origin: french
