error_404_entry: c903e7b3-8c6c-454e-8821-c9b29ff64ede
copyright_name: 'Philippe Pasquin (Développeur Shopify)'
copyright_since: 2020
privacy_statement_type: none
cookie_notice_type: none
logo: pp-(dalee)-logo-(40-x-40-px).svg
voir_le_prix: 'Voir le prix'
voir_les_prix: 'Voir les prix'
request_price: 'Demander un estimé'
