error_404_entry: c903e7b3-8c6c-454e-8821-c9b29ff64ede
copyright_name: 'Philippe Pasquin (Développeur Shopify)'
copyright_since: 2020
privacy_statement_type: none
cookie_notice_type: none
logo: milistack_screenshot-2023-11-28-10.42.26.png
voir_le_prix: 'Voir le prix'
voir_les_prix: 'Voir les prix'
request_price: 'Demander un estimé'
commencons: Commençons!
pricing_page: e785a253-1496-4e04-84e8-5162700ba43b
subheading: 'Support sur mesure sur Shopify'
heading: 'Déléguez vos tâches de développement Shopify.'
description: 'Choisissez un plan qui fonctionne pour vous'
