title: 'Boutique Shopify existante'
updated_by: cd3700e4-11c6-42b6-8dbb-6134449b1279
updated_at: 1699566845
blueprint: services_type
order: 2
localizations:
  'English CA':
    title: 'Existing Shopify Store'
    slug: boutique-shopify-existante
    updated_by: cd3700e4-11c6-42b6-8dbb-6134449b1279
    updated_at: 1702314406
  'English US':
    title: 'Existing Shopify Store'
    slug: boutique-shopify-existante
    updated_by: cd3700e4-11c6-42b6-8dbb-6134449b1279
    updated_at: 1702314426
