copyright_name: 'Philippe Pasquin (Shopify Partner & Expert)'
voir_le_prix: 'See the price'
voir_les_prix: 'See the prices'
request_price: 'Request a quote'
commencons: "Let's get started!"
origin: french
