title: Services
sites:
  - french
  - 'English CA'
  - 'English US'
propagate: false
template: services/layout
layout: layout
taxonomies:
  - services_type
revisions: false
route:
  french: '/solutions/{slug}'
  'English CA': '/services/{slug}'
  'English US': '/services/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
origin_behavior: root
structure:
  root: false
  slugs: true
