tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              localizable: true
              validate:
                - required
          -
            handle: menu_description
            field:
              antlers: false
              type: textarea
              display: 'Menu Description'
              icon: textarea
              localizable: true
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
    seo:
        display: SEO
        sections:
          -
            display: Basic
            instructions: 'Basic SEO settings.'
            fields:
              -
                import: 'statamic-peak-seo::seo_basic'
          -
            display: Advanced
            instructions: 'Advanced SEO settings.'
            fields:
              -
                import: 'statamic-peak-seo::seo_advanced'
          -
            display: 'Open Graph'
            instructions: 'Open Graph meta tags for social sharing.'
            fields:
              -
                import: 'statamic-peak-seo::seo_open_graph'
          -
            display: Sitemap
            instructions: 'Sitemap configuration.'
            fields:
              -
                import: 'statamic-peak-seo::seo_sitemap'
          -
            display: 'JSON-ld Schema'
            instructions: 'Custom JSON-ld schema objects.'
            fields:
              -
                import: 'statamic-peak-seo::seo_jsonld'
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
          -
            handle: parent
            field:
              type: entries
              collections:
                - services
              max_items: 1
              listable: false
              localizable: true
          -
            handle: services_type
            field:
              type: terms
              taxonomies:
                - services_type
              display: 'Services Type'
              mode: default
              max_items: 1
              create: true
              icon: taxonomy
              localizable: false
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            import: gradient
title: Service
