tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              localizable: true
              validate:
                - required
          -
            handle: menu_description
            field:
              antlers: false
              type: textarea
              display: 'Menu Description'
              icon: textarea
              localizable: true
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
      -
        display: 'Service Page'
        fields:
          -
            handle: turnaround
            field:
              input_type: text
              antlers: false
              type: text
              display: Turnaround
              icon: text
              instructions: Optional
              localizable: true
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: left_right
            field:
              collapse: false
              previews: true
              fullscreen: true
              sets:
                new_set_group:
                  display: 'New Set Group'
                  instructions: null
                  icon: null
                  sets:
                    left_right_block:
                      display: 'Left Right Block'
                      instructions: null
                      icon: null
                      fields:
                        -
                          handle: image
                          field:
                            mode: list
                            restrict: false
                            allow_uploads: true
                            show_filename: true
                            show_set_alt: true
                            type: assets
                            display: Image
                            icon: assets
                            localizable: true
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            replicator_preview: true
                            hide_display: false
                            max_files: 1
                            container: images
                        -
                          handle: heading
                          field:
                            buttons:
                              - bold
                              - italic
                            smart_typography: false
                            save_html: false
                            inline: false
                            toolbar_mode: fixed
                            reading_time: false
                            word_count: false
                            fullscreen: true
                            allow_source: true
                            enable_input_rules: true
                            enable_paste_rules: true
                            remove_empty_nodes: false
                            antlers: false
                            link_noopener: false
                            link_noreferrer: false
                            target_blank: false
                            always_show_set_button: false
                            collapse: false
                            previews: true
                            type: bard
                            display: Heading
                            icon: bard
                            localizable: true
                            width: 50
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            replicator_preview: true
                            hide_display: false
                        -
                          handle: paragraph
                          field:
                            buttons:
                              - bold
                              - italic
                              - unorderedlist
                              - orderedlist
                              - anchor
                            smart_typography: false
                            save_html: false
                            inline: false
                            toolbar_mode: fixed
                            reading_time: false
                            word_count: false
                            fullscreen: true
                            allow_source: true
                            enable_input_rules: true
                            enable_paste_rules: true
                            remove_empty_nodes: false
                            antlers: false
                            link_noopener: false
                            link_noreferrer: false
                            target_blank: false
                            always_show_set_button: false
                            collapse: false
                            previews: true
                            type: bard
                            display: Paragraph
                            icon: bard
                            localizable: true
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            replicator_preview: true
                            hide_display: false
                        -
                          import: buttons
              type: replicator
              display: 'Left Right'
              icon: replicator
              localizable: true
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
      -
        display: Pricing
        fields:
          -
            import: pricings
            prefix: services
  seo:
    display: SEO
    sections:
      -
        display: 'New Section'
        fields:
          -
            import: seo_full
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: parent
            field:
              type: entries
              collections:
                - services
              max_items: 1
              listable: false
              localizable: true
          -
            handle: services_type
            field:
              type: terms
              taxonomies:
                - services_type
              display: 'Services Type'
              mode: default
              max_items: 1
              create: true
              icon: taxonomy
              localizable: false
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            import: gradient
title: Service
